In [ ]:
import numpy as np

In [ ]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [ ]:
A = vector + matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [ ]:
A = matriz.T + vector

In [ ]:
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [ ]:
C = matriz + 42

In [ ]:
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [ ]:
D = matriz + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]
