In [ ]:
import numpy as np

In [ ]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [ ]:
A = matriz * vector

In [ ]:
B = matriz.dot(vector)

In [ ]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [ ]:
print(B)

[ 8 18 28]


In [ ]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]


In [ ]:
D = np.array([[2],[2],[2]])

In [ ]:
print(D)

[[2]
 [2]
 [2]]
